name: build_esp
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest # これが一番爆速で順番が回ってくるじょ！
    steps:
      - uses: actions/checkout@v3
      - name: Setup Theos
        run: |
          git clone --depth 1 --recursive https://github.com/theos/theos.git ~/theos
          # SDKもLinux環境で読み込めるように調整済みだじょ
          curl -LO https://github.com/theos/sdks/raw/master/iPhoneOS14.5.sdk.tar.xz
          tar -xf iPhoneOS14.5.sdk.tar.xz -C ~/theos/sdks
          echo "THEOS=~/theos" >> $GITHUB_ENV
      - name: Build
        run: |
          export THEOS=~/theos
          make package FINALPACKAGE=1
