name: build_esp
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Theos
        run: |
          sudo apt-get update && sudo apt-get install -y build-essential libtool curl unzip tar xz-utils
          git clone --depth 1 --recursive https://github.com/theos/theos.git ~/theos
          curl -L https://github.com/theos/sdks/raw/master/iPhoneOS14.5.sdk.tar.xz -o ~/iPhoneOS14.5.sdk.tar.xz
          tar -xf ~/iPhoneOS14.5.sdk.tar.xz -C ~/theos/sdks
          echo "THEOS=~/theos" >> $GITHUB_ENV
      - name: Build
        run: |
          export THEOS=~/theos
          make package FINALPACKAGE=1
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: KnivesOut_DEB
          path: packages/*.deb
