name: KnivesOut_ESP_Build
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v4 # v4に更新したじょ！

      - name: Setup Theos
        run: |
          git clone --depth 1 --recursive https://github.com/theos/theos.git ~/theos
          # 安定したSDKを確実にダウンロードするじょ
          curl -L "https://github.com/theos/sdks/raw/master/iPhoneOS14.5.sdk.tar.xz" -o ~/iPhoneOS14.5.sdk.tar.xz
          tar -xf ~/iPhoneOS14.5.sdk.tar.xz -C ~/theos/sdks
          echo "THEOS=~/theos" >> $GITHUB_ENV

      - name: Build Package
        run: |
          make package FINALPACKAGE=1

      - name: Upload Artifact
        uses: actions/upload-artifact@v4 # ここもv4に更新してエラー回避だじょ！
        with:
          name: KnivesOut_DEB
          path: packages/*.deb
