name: KnivesOut_ESP_Build
on: [push, workflow_dispatch]

jobs:
  build:
    # 混んでいる macos-12 をやめて、爆速の ubuntu に変更！
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          # Ubuntuでビルドするために必要な道具を最初に入れるじょ
          sudo apt-get update && sudo apt-get install -y build-essential libtool curl unzip tar xz-utils
          git clone --depth 1 --recursive https://github.com/theos/theos.git ~/theos
          
          # SDKを安定した場所からダウンロード
          curl -L "https://github.com/theos/sdks/raw/master/iPhoneOS14.5.sdk.tar.xz" -o ~/iPhoneOS14.5.sdk.tar.xz
          tar -xf ~/iPhoneOS14.5.sdk.tar.xz -C ~/theos/sdks
          echo "THEOS=~/theos" >> $GITHUB_ENV

      - name: Build Package
        run: |
          # Ubuntu上でiOS用のビルドを走らせる呪文だじょ！
          export THEOS=~/theos
          make package FINALPACKAGE=1

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: KnivesOut_DEB
          path: packages/*.deb
